{
  lib,
  runCommand,
  sessionVariables ? { },
}:
let
  inherit (lib)
    concatStrings
    mapAttrsToList
    ;

  content = concatStrings (
    mapAttrsToList (name: value: "export ${name}=${value}\n") sessionVariables
  );

  header = "# Session variabled generated by nix-heim, do not edit!\n";
in
runCommand "heim-environment" { } ''
    mkdir -p $out/share/heim
    cat > $out/share/heim/session-vars.sh <<EOF
  ${header}${content}
  EOF
''
